service: api-gateway-signup

frameworkVersion: '2'


provider:
  name: aws
  stage: ${opt:stage,'dev'}
  runtime: nodejs12.x
  timeout: 60
  apiName: apigateway-fetch-metadata
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/${opt:stage, self:provider.stage}/POST/metadata
      
plugins:
  - serverless-pseudo-parameters


functions:
  gatewayLambda: ${file(./gatewayLambda.yml):gatewayLambda}